// ============================================================
//  PRODUCTS DATA — Edit this file to add/remove/change products
//  For each product, place the image inside the /images/ folder
//  and set the "image" field to "images/your-filename.jpg"
// ============================================================

const PRODUCTS = [
  {
    id: 1,
    name: "Wireless Headphones",
    price: 79.99,
    originalPrice: 109.99,
    category: "electronics",
    image: "images/product1.jpg",       // ← add product1.jpg to /images/
    badge: "Sale",
    rating: 4.5,
    reviews: 128,
    description: "Premium over-ear headphones with 30-hour battery life, active noise cancellation, and crystal-clear sound. Perfect for work and travel.",
    featured: true
  },
  {
    id: 2,
    name: "Classic White Tee",
    price: 29.99,
    originalPrice: null,
    category: "clothing",
    image: "images/product2.jpg",       // ← add product2.jpg to /images/
    badge: null,
    rating: 4.8,
    reviews: 342,
    description: "100% organic cotton crew-neck tee. Soft, breathable, and built to last. Available in sizes XS–XXL.",
    featured: true
  },
  {
    id: 3,
    name: "Leather Watch",
    price: 149.99,
    originalPrice: null,
    category: "accessories",
    image: "images/product3.jpg",
    badge: "New",
    rating: 4.6,
    reviews: 87,
    description: "Minimalist quartz watch with genuine leather strap and scratch-resistant sapphire glass. Water-resistant to 50m.",
    featured: true
  },
  {
    id: 4,
    name: "Ceramic Desk Lamp",
    price: 64.99,
    originalPrice: 84.99,
    category: "home",
    image: "images/product4.jpg",
    badge: "Sale",
    rating: 4.3,
    reviews: 55,
    description: "Handcrafted ceramic base with adjustable warm/cool LED. USB-C charging port built into the base.",
    featured: true
  },
  {
    id: 5,
    name: "Running Sneakers",
    price: 119.99,
    originalPrice: null,
    category: "clothing",
    image: "images/product5.jpg",
    badge: null,
    rating: 4.7,
    reviews: 201,
    description: "Lightweight mesh upper with responsive foam sole. Designed for daily training runs and all-day comfort.",
    featured: false
  },
  {
    id: 6,
    name: "Portable Speaker",
    price: 59.99,
    originalPrice: 79.99,
    category: "electronics",
    image: "images/product6.jpg",
    badge: "Sale",
    rating: 4.4,
    reviews: 163,
    description: "360° sound with 12-hour playtime and IPX7 waterproof rating. Pairs instantly via Bluetooth 5.0.",
    featured: false
  },
  {
    id: 7,
    name: "Canvas Tote Bag",
    price: 24.99,
    originalPrice: null,
    category: "accessories",
    image: "images/product7.jpg",
    badge: null,
    rating: 4.9,
    reviews: 477,
    description: "Heavy-duty canvas with reinforced stitching and interior zip pocket. Holds up to 20kg.",
    featured: false
  },
  {
    id: 8,
    name: "Scented Candle Set",
    price: 39.99,
    originalPrice: null,
    category: "home",
    image: "images/product8.jpg",
    badge: "New",
    rating: 4.6,
    reviews: 92,
    description: "Set of 3 hand-poured soy wax candles: Cedarwood, Vanilla Amber, and Fresh Linen. 45-hour burn time each.",
    featured: false
  },
  {
    id: 9,             
    name: "Mechanical Keyboard",
    price: 89.99,
    originalPrice: null,
    category: "electronics",
    image: "images/product9.jpg",
    badge: null,        
    rating: 4.6,
    reviews: 74,
    description: "Your product description here.",
    featured: false     
},
{
  id: 10,
  name: "Wireless Mouse",
  price: 39.99,
  originalPrice: null,
  category: "electronics",
  image: "images/product10.jpg",
  badge: null,
  rating: 4.5,
  reviews: 187,
  description: "Ergonomic wireless mouse with 12-month battery life, silent clicks, and 3-device Bluetooth switching. Works on any surface.",
  featured: false
},
{
  id: 11,
  name: "Hoodie",
  price: 54.99,
  originalPrice: null,
  category: "clothing",
  image: "images/product11.jpg",
  badge: "New",
  rating: 4.8,
  reviews: 302,
  description: "Heavyweight 400gsm fleece hoodie with kangaroo pocket and adjustable drawstring. Pre-shrunk and stone-washed for a lived-in feel.",
  featured: false
},
{
  id: 12,
  name: "Denim Jacket",
  price: 79.99,
  originalPrice: 99.99,
  category: "clothing",
  image: "images/product12.jpg",
  badge: "Sale",
  rating: 4.6,
  reviews: 145,
  description: "Classic fit denim jacket in mid-wash blue. Double chest pockets, reinforced stitching, and a slightly cropped silhouette.",
  featured: false
},
{
  id: 13,
  name: "Sunglasses",
  price: 34.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product13.jpg",
  badge: null,
  rating: 4.4,
  reviews: 98,
  description: "Polarised UV400 lenses in a lightweight acetate frame. Comes with a hard case and microfibre cleaning cloth.",
  featured: false
},
{
  id: 14,
  name: "Minimalist Wallet",
  price: 29.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product14.jpg",
  badge: "New",
  rating: 4.9,
  reviews: 411,
  description: "Slim bifold wallet in genuine full-grain leather. Holds up to 8 cards and cash. Gets better with age.",
  featured: false
},
{
  id: 15,
  name: "Throw Pillow Set",
  price: 44.99,
  originalPrice: 59.99,
  category: "home",
  image: "images/product15.jpg",
  badge: "Sale",
  rating: 4.5,
  reviews: 134,
  description: "Set of 2 linen-blend throw pillows with removable zip covers. Available in neutral tones to complement any sofa or bed.",
  featured: false
},
{
  id: 16,
  name: "Wall Clock",
  price: 49.99,
  originalPrice: null,
  category: "home",
  image: "images/product16.jpg",
  badge: null,
  rating: 4.6,
  reviews: 76,
  description: "Silent sweep 30cm wall clock with a brushed brass frame and minimalist dial. AA battery included.",
  featured: false
},
{
  id: 17,
  name: "Power Bank",
  price: 49.99,
  originalPrice: 64.99,
  category: "electronics",
  image: "images/product17.jpg",
  badge: "Sale",
  rating: 4.7,
  reviews: 289,
  description: "20,000mAh power bank with 65W USB-C fast charging. Charges a laptop, phone, and tablet simultaneously.",
  featured: false
},
{
  id: 18,
  name: "Linen Shirt",
  price: 49.99,
  originalPrice: null,
  category: "clothing",
  image: "images/product18.jpg",
  badge: "New",
  rating: 4.7,
  reviews: 167,
  description: "100% stonewashed linen shirt with a relaxed fit and chest pocket. Breathable and perfect for warm weather.",
  featured: false
},
{
  id: 19,
  name: "Ceramic Mug Set",
  price: 34.99,
  originalPrice: null,
  category: "home",
  image: "images/product19.jpg",
  badge: null,
  rating: 4.8,
  reviews: 223,
  description: "Set of 4 handcrafted ceramic mugs in matte earth tones. Dishwasher safe, 350ml capacity each.",
  featured: false
},
{
  id: 21,
  name: "Noise Cancelling Earbuds",
  price: 99.99,
  originalPrice: 129.99,
  category: "electronics",
  image: "images/product21.jpg",
  badge: "Sale",
  rating: 4.7,
  reviews: 334,
  description: "True wireless earbuds with hybrid active noise cancellation, 8-hour battery life, and IPX5 water resistance. Includes 3 ear tip sizes.",
  featured: false
},
{
  id: 22,
  name: "USB-C Hub",
  price: 44.99,
  originalPrice: null,
  category: "electronics",
  image: "images/product22.jpg",
  badge: null,
  rating: 4.6,
  reviews: 198,
  description: "7-in-1 USB-C hub with 4K HDMI, 3x USB-A, SD card reader, and 100W pass-through charging. Plug and play, no drivers needed.",
  featured: false
},
{
  id: 23,
  name: "Smart LED Bulb",
  price: 19.99,
  originalPrice: null,
  category: "electronics",
  image: "images/product23.jpg",
  badge: "New",
  rating: 4.5,
  reviews: 412,
  description: "Wi-Fi smart bulb with 16 million colours and warm-to-cool white range. Works with Alexa, Google Home, and app control.",
  featured: false
},
{
  id: 24,
  name: "Webcam 1080p",
  price: 69.99,
  originalPrice: 89.99,
  category: "electronics",
  image: "images/product24.jpg",
  badge: "Sale",
  rating: 4.6,
  reviews: 156,
  description: "Full HD 1080p webcam with built-in stereo microphone, auto light correction, and privacy cover. Plug and play via USB-A.",
  featured: false
},
{
  id: 25,
  name: "Phone Stand",
  price: 17.99,
  originalPrice: null,
  category: "electronics",
  image: "images/product25.jpg",
  badge: null,
  rating: 4.8,
  reviews: 527,
  description: "Adjustable aluminium desk phone stand. Foldable, compatible with all phone sizes, and doubles as a tablet holder.",
  featured: false
},
{
  id: 26,
  name: "Laptop Sleeve",
  price: 27.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product26.jpg",
  badge: null,
  rating: 4.7,
  reviews: 243,
  description: "Water-resistant neoprene laptop sleeve with accessory pocket. Fits 13–14 inch laptops. Available in charcoal and navy.",
  featured: false
},
{
  id: 27,
  name: "Beanie Hat",
  price: 19.99,
  originalPrice: null,
  category: "clothing",
  image: "images/product27.jpg",
  badge: "New",
  rating: 4.9,
  reviews: 381,
  description: "Soft ribbed merino wool beanie. One size fits most. Naturally warm, itch-free, and machine washable.",
  featured: false
},
{
  id: 28,
  name: "Jogger Pants",
  price: 44.99,
  originalPrice: 59.99,
  category: "clothing",
  image: "images/product28.jpg",
  badge: "Sale",
  rating: 4.6,
  reviews: 274,
  description: "French terry joggers with tapered leg, deep side pockets, and elastic waistband with drawstring. Ideal for the gym or lounging.",
  featured: false
},
{
  id: 29,
  name: "Sports Bra",
  price: 34.99,
  originalPrice: null,
  category: "clothing",
  image: "images/product29.jpg",
  badge: null,
  rating: 4.7,
  reviews: 319,
  description: "Medium-support sports bra with moisture-wicking fabric, removable cups, and a racerback design. Sizes XS–XL.",
  featured: false
},
{
  id: 30,
  name: "Baseball Cap",
  price: 22.99,
  originalPrice: null,
  category: "clothing",
  image: "images/product30.jpg",
  badge: null,
  rating: 4.5,
  reviews: 188,
  description: "Unstructured 6-panel cap in washed cotton twill. Adjustable strap, one size fits all. Fades beautifully with wear.",
  featured: false
},
{
  id: 31,
  name: "Compression Socks Set",
  price: 24.99,
  originalPrice: null,
  category: "clothing",
  image: "images/product31.jpg",
  badge: "New",
  rating: 4.6,
  reviews: 142,
  description: "Pack of 5 pairs of graduated compression socks. Reduces fatigue and improves circulation. Great for travel and long shifts.",
  featured: false
},
{
  id: 32,
  name: "Puffer Vest",
  price: 64.99,
  originalPrice: 84.99,
  category: "clothing",
  image: "images/product32.jpg",
  badge: "Sale",
  rating: 4.7,
  reviews: 96,
  description: "Lightweight quilted puffer vest with recycled fill, two zip pockets, and a packable design. Unisex sizing.",
  featured: false
},
{
  id: 33,
  name: "Silk Scrunchie Set",
  price: 16.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product33.jpg",
  badge: null,
  rating: 4.8,
  reviews: 503,
  description: "Set of 6 mulberry silk scrunchies in assorted neutral tones. Gentle on hair, no creases, and reusable.",
  featured: false
},
{
  id: 34,
  name: "Gold Hoop Earrings",
  price: 21.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product34.jpg",
  badge: "New",
  rating: 4.7,
  reviews: 267,
  description: "14K gold-plated sterling silver hoop earrings, 30mm diameter. Hypoallergenic and tarnish-resistant.",
  featured: false
},
{
  id: 35,
  name: "Leather Belt",
  price: 32.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product35.jpg",
  badge: null,
  rating: 4.6,
  reviews: 174,
  description: "Full-grain leather belt with a brushed silver pin buckle. 35mm width, available in sizes 28–42 inches.",
  featured: false
},
{
  id: 36,
  name: "Minimalist Necklace",
  price: 26.99,
  originalPrice: 34.99,
  category: "accessories",
  image: "images/product36.jpg",
  badge: "Sale",
  rating: 4.8,
  reviews: 388,
  description: "Dainty 18K gold-plated chain necklace with a small bar pendant. 45cm length with a 5cm extender.",
  featured: false
},
{
  id: 37,
  name: "Phone Case",
  price: 14.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product37.jpg",
  badge: null,
  rating: 4.5,
  reviews: 631,
  description: "Slim frosted matte hard case with reinforced corners. Available for iPhone and Samsung Galaxy models. Wireless charging compatible.",
  featured: false
},
{
  id: 38,
  name: "Keychain Multi-tool",
  price: 18.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product38.jpg",
  badge: "New",
  rating: 4.7,
  reviews: 209,
  description: "Compact 8-in-1 stainless steel keychain tool with bottle opener, screwdrivers, and ruler. TSA-compliant.",
  featured: false
},
{
  id: 39,
  name: "Passport Holder",
  price: 19.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product39.jpg",
  badge: null,
  rating: 4.8,
  reviews: 317,
  description: "Vegan leather passport holder with RFID blocking, 4 card slots, and a boarding pass pocket. Fits all passport sizes.",
  featured: false
},
{
  id: 40,
  name: "Gym Duffel Bag",
  price: 49.99,
  originalPrice: 64.99,
  category: "accessories",
  image: "images/product40.jpg",
  badge: "Sale",
  rating: 4.6,
  reviews: 183,
  description: "40L gym bag with separate wet/dry compartment, shoe pocket, and adjustable shoulder strap. Water-resistant base.",
  featured: false
},
{
  id: 41,
  name: "Diffuser",
  price: 42.99,
  originalPrice: null,
  category: "home",
  image: "images/product41.jpg",
  badge: "New",
  rating: 4.7,
  reviews: 261,
  description: "Ultrasonic aromatherapy diffuser with 7 LED colour modes, auto shut-off, and 400ml capacity. Runs up to 10 hours continuously.",
  featured: false
},
{
  id: 42,
  name: "Storage Basket Set",
  price: 37.99,
  originalPrice: null,
  category: "home",
  image: "images/product42.jpg",
  badge: null,
  rating: 4.6,
  reviews: 148,
  description: "Set of 3 seagrass woven baskets in nesting sizes. Ideal for blankets, toys, or bathroom storage. Handles included.",
  featured: false
},
{
  id: 43,
  name: "Bamboo Cutting Board",
  price: 29.99,
  originalPrice: null,
  category: "home",
  image: "images/product43.jpg",
  badge: null,
  rating: 4.8,
  reviews: 432,
  description: "Extra-large bamboo cutting board with juice groove, built-in handles, and non-slip feet. 45x30cm. Dishwasher safe.",
  featured: false
},
{
  id: 44,
  name: "Picture Frame Set",
  price: 34.99,
  originalPrice: 44.99,
  category: "home",
  image: "images/product44.jpg",
  badge: "Sale",
  rating: 4.5,
  reviews: 117,
  description: "Set of 5 black gallery frames in sizes 4x6, 5x7, and 8x10 inches. Shatter-resistant glass and wall-mount hardware included.",
  featured: false
},
{
  id: 45,
  name: "Plant Pot Set",
  price: 32.99,
  originalPrice: null,
  category: "home",
  image: "images/product45.jpg",
  badge: "New",
  rating: 4.7,
  reviews: 199,
  description: "Set of 3 speckled ceramic plant pots with drainage holes and matching saucers. Sizes: 10cm, 14cm, and 18cm.",
  featured: false
},
{
  id: 46,
  name: "Weighted Blanket",
  price: 79.99,
  originalPrice: 99.99,
  category: "home",
  image: "images/product46.jpg",
  badge: "Sale",
  rating: 4.8,
  reviews: 354,
  description: "7kg weighted blanket with glass bead fill and removable minky cover. 150x200cm. Promotes deeper, more restful sleep.",
  featured: false
},
{
  id: 47,
  name: "Yoga Mat",
  price: 54.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product47.jpg",
  badge: null,
  rating: 4.7,
  reviews: 278,
  description: "6mm non-slip natural rubber yoga mat with alignment lines and carrying strap. 183x61cm. Sweat-resistant surface.",
  featured: false
},
{
  id: 48,
  name: "Resistance Bands Set",
  price: 22.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product48.jpg",
  badge: "New",
  rating: 4.6,
  reviews: 391,
  description: "Set of 5 latex resistance bands in light to extra-heavy resistance levels. Includes carry bag and exercise guide.",
  featured: false
},
{
  id: 49,
  name: "Water Bottle",
  price: 29.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product49.jpg",
  badge: null,
  rating: 4.9,
  reviews: 712,
  description: "500ml double-wall stainless steel bottle. Keeps drinks cold 24hr and hot 12hr. Leak-proof lid and wide mouth design.",
  featured: false
},
{
  id: 50,
  name: "Foam Roller",
  price: 27.99,
  originalPrice: 34.99,
  category: "accessories",
  image: "images/product50.jpg",
  badge: "Sale",
  rating: 4.6,
  reviews: 163,
  description: "High-density EVA foam roller for muscle recovery and myofascial release. 33cm length, supports up to 150kg.",
  featured: false
},
{
  id: 51,
  name: "Digital Kitchen Scale",
  price: 23.99,
  originalPrice: null,
  category: "home",
  image: "images/product51.jpg",
  badge: null,
  rating: 4.7,
  reviews: 294,
  description: "Precision kitchen scale with 1g accuracy up to 5kg. Slim tempered glass platform, tare function, and USB charging.",
  featured: false
},
{
  id: 52,
  name: "French Press",
  price: 36.99,
  originalPrice: null,
  category: "home",
  image: "images/product52.jpg",
  badge: "New",
  rating: 4.8,
  reviews: 447,
  description: "1L borosilicate glass French press with stainless steel plunger and double-wall insulated frame. Makes 4 cups.",
  featured: false
},
{
  id: 53,
  name: "Spice Rack",
  price: 31.99,
  originalPrice: 39.99,
  category: "home",
  image: "images/product53.jpg",
  badge: "Sale",
  rating: 4.5,
  reviews: 128,
  description: "Wall-mounted bamboo spice rack with 12 uniform glass jars and labels. Easy to install, no tools required.",
  featured: false
},
{
  id: 54,
  name: "Linen Duvet Cover",
  price: 89.99,
  originalPrice: null,
  category: "home",
  image: "images/product54.jpg",
  badge: null,
  rating: 4.8,
  reviews: 213,
  description: "100% French linen duvet cover with button closure and corner ties. Pre-washed for softness. Available in king and queen.",
  featured: false
},
{
  id: 55,
  name: "Desk Organiser",
  price: 26.99,
  originalPrice: null,
  category: "home",
  image: "images/product55.jpg",
  badge: "New",
  rating: 4.6,
  reviews: 187,
  description: "Bamboo desk organiser with 5 compartments for pens, cards, and stationery. Compact design fits most desks.",
  featured: false
},
{
  id: 56,
  name: "Portable Blender",
  price: 38.99,
  originalPrice: 49.99,
  category: "electronics",
  image: "images/product56.jpg",
  badge: "Sale",
  rating: 4.5,
  reviews: 302,
  description: "USB-C rechargeable portable blender with 380ml BPA-free cup. 6 stainless steel blades. Perfect for smoothies on the go.",
  featured: false
},
{
  id: 57,
  name: "Smart Watch",
  price: 129.99,
  originalPrice: 159.99,
  category: "electronics",
  image: "images/product57.jpg",
  badge: "Sale",
  rating: 4.6,
  reviews: 381,
  description: "1.7-inch AMOLED smartwatch with health monitoring, GPS, sleep tracking, and 7-day battery life. IP68 waterproof.",
  featured: false
},
{
  id: 58,
  name: "Ring Light",
  price: 44.99,
  originalPrice: null,
  category: "electronics",
  image: "images/product58.jpg",
  badge: null,
  rating: 4.7,
  reviews: 263,
  description: "10-inch bi-colour LED ring light with adjustable stand, phone holder, and remote. 3 colour modes and 10 brightness levels.",
  featured: false
},
{
  id: 59,
  name: "Surge Protector",
  price: 32.99,
  originalPrice: null,
  category: "electronics",
  image: "images/product59.jpg",
  badge: "New",
  rating: 4.8,
  reviews: 519,
  description: "6-outlet surge protector with 3 USB-A and 1 USB-C port. 1.8m braided cable, 2500J surge protection rating.",
  featured: false
},
{
  id: 60,
  name: "Cable Management Box",
  price: 21.99,
  originalPrice: null,
  category: "home",
  image: "images/product60.jpg",
  badge: null,
  rating: 4.6,
  reviews: 344,
  description: "Large plastic cable management box that hides power strips and tangled cables. 36x13x12cm, snap-lid design.",
  featured: false
},
{
  id: 61,
  name: "Graphic Print Tee",
  price: 27.99,
  originalPrice: null,
  category: "clothing",
  image: "images/product61.jpg",
  badge: "New",
  rating: 4.5,
  reviews: 194,
  description: "100% combed cotton graphic tee with oversized fit and chest print. Available in sizes S–XXL. Pre-shrunk.",
  featured: false
},
{
  id: 62,
  name: "Chino Trousers",
  price: 59.99,
  originalPrice: 74.99,
  category: "clothing",
  image: "images/product62.jpg",
  badge: "Sale",
  rating: 4.6,
  reviews: 212,
  description: "Slim-fit stretch chino trousers with hidden waistband adjuster and two back pockets. Wrinkle-resistant fabric.",
  featured: false
},
{
  id: 63,
  name: "Swim Shorts",
  price: 32.99,
  originalPrice: null,
  category: "clothing",
  image: "images/product63.jpg",
  badge: null,
  rating: 4.7,
  reviews: 138,
  description: "Quick-dry recycled polyester swim shorts with mesh lining, elastic waist, and zip pocket. Length: mid-thigh.",
  featured: false
},
{
  id: 64,
  name: "Trench Coat",
  price: 119.99,
  originalPrice: 149.99,
  category: "clothing",
  image: "images/product64.jpg",
  badge: "Sale",
  rating: 4.8,
  reviews: 87,
  description: "Classic double-breasted trench coat in water-repellent cotton blend. Belt included. Available in camel and black.",
  featured: false
},
{
  id: 65,
  name: "Polo Shirt",
  price: 39.99,
  originalPrice: null,
  category: "clothing",
  image: "images/product65.jpg",
  badge: null,
  rating: 4.6,
  reviews: 221,
  description: "Pique cotton polo with two-button placket and embroidered chest logo. Slim fit. Machine washable.",
  featured: false
},
{
  id: 66,
  name: "Ankle Boots",
  price: 89.99,
  originalPrice: 114.99,
  category: "clothing",
  image: "images/product66.jpg",
  badge: "Sale",
  rating: 4.7,
  reviews: 173,
  description: "Chelsea-style ankle boots in vegan leather with elastic side panels and a stacked 4cm heel. Sizes 36–45.",
  featured: false
},
{
  id: 67,
  name: "Slide Sandals",
  price: 29.99,
  originalPrice: null,
  category: "clothing",
  image: "images/product67.jpg",
  badge: "New",
  rating: 4.5,
  reviews: 309,
  description: "Cushioned EVA slide sandals with adjustable single-strap. Lightweight, water-friendly, and perfect for summer.",
  featured: false
},
{
  id: 68,
  name: "Crossbody Bag",
  price: 44.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product68.jpg",
  badge: null,
  rating: 4.7,
  reviews: 258,
  description: "Compact vegan leather crossbody bag with zip closure, interior card slots, and adjustable 120cm strap.",
  featured: false
},
{
  id: 69,
  name: "Silk Pillowcase",
  price: 34.99,
  originalPrice: null,
  category: "home",
  image: "images/product69.jpg",
  badge: "New",
  rating: 4.9,
  reviews: 486,
  description: "22 momme mulberry silk pillowcase with hidden zip. Reduces friction for hair and skin. Standard and king sizes available.",
  featured: false
},
{
  id: 70,
  name: "Acrylic Organiser",
  price: 28.99,
  originalPrice: 36.99,
  category: "home",
  image: "images/product70.jpg",
  badge: "Sale",
  rating: 4.6,
  reviews: 167,
  description: "Clear acrylic makeup and skincare organiser with 15 compartments. Stackable design, easy to clean.",
  featured: false
},
{
  id: 71,
  name: "Reusable Produce Bags",
  price: 14.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product71.jpg",
  badge: null,
  rating: 4.8,
  reviews: 423,
  description: "Set of 9 organic cotton mesh produce bags in 3 sizes. Washable, zero-waste alternative to plastic produce bags.",
  featured: false
},
{
  id: 72,
  name: "Bamboo Toothbrush Set",
  price: 12.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product72.jpg",
  badge: "New",
  rating: 4.7,
  reviews: 341,
  description: "Pack of 4 biodegradable bamboo toothbrushes with charcoal-infused BPA-free bristles. Compostable packaging.",
  featured: false
},
{
  id: 73,
  name: "Stainless Steel Straw Set",
  price: 11.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product73.jpg",
  badge: null,
  rating: 4.6,
  reviews: 289,
  description: "Set of 8 reusable stainless steel straws in 2 sizes with cleaning brushes and a travel pouch. Dishwasher safe.",
  featured: false
},
{
  id: 74,
  name: "Beeswax Wraps",
  price: 16.99,
  originalPrice: null,
  category: "home",
  image: "images/product74.jpg",
  badge: "New",
  rating: 4.7,
  reviews: 198,
  description: "Pack of 3 reusable beeswax food wraps in small, medium, and large. Natural alternative to cling film. Washable and compostable.",
  featured: false
},
{
  id: 75,
  name: "Wooden Serving Board",
  price: 38.99,
  originalPrice: 49.99,
  category: "home",
  image: "images/product75.jpg",
  badge: "Sale",
  rating: 4.8,
  reviews: 163,
  description: "Acacia wood charcuterie and serving board, 50x25cm. Live-edge design with hanging hole and pre-oiled finish.",
  featured: false
},
{
  id: 76,
  name: "Insulated Lunch Bag",
  price: 22.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product76.jpg",
  badge: null,
  rating: 4.6,
  reviews: 274,
  description: "6L insulated lunch bag with leakproof lining, front pocket, and shoulder strap. Keeps food fresh for up to 6 hours.",
  featured: false
},
{
  id: 77,
  name: "Desk Pad",
  price: 24.99,
  originalPrice: null,
  category: "home",
  image: "images/product77.jpg",
  badge: "New",
  rating: 4.7,
  reviews: 388,
  description: "Large 90x40cm PU leather desk pad with non-slip base. Waterproof surface protects your desk and anchors your setup.",
  featured: false
},
{
  id: 78,
  name: "Monitor Stand",
  price: 41.99,
  originalPrice: 54.99,
  category: "home",
  image: "images/product78.jpg",
  badge: "Sale",
  rating: 4.7,
  reviews: 219,
  description: "Bamboo monitor riser with open storage shelf underneath. Supports up to 20kg. Compatible with 13–32 inch screens.",
  featured: false
},
{
  id: 79,
  name: "Journaling Notebook",
  price: 18.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product79.jpg",
  badge: null,
  rating: 4.9,
  reviews: 534,
  description: "A5 hardcover dotted notebook with 200 pages of 120gsm ivory paper. Lay-flat binding and ribbon bookmark.",
  featured: false
},
{
  id: 80,
  name: "Gel Pen Set",
  price: 14.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product80.jpg",
  badge: "New",
  rating: 4.7,
  reviews: 312,
  description: "Set of 20 smooth-writing gel pens in assorted colours. 0.7mm tip, quick-drying ink, comfortable grip.",
  featured: false
},
{
  id: 81,
  name: "Acupressure Mat",
  price: 46.99,
  originalPrice: 59.99,
  category: "accessories",
  image: "images/product81.jpg",
  badge: "Sale",
  rating: 4.6,
  reviews: 201,
  description: "Linen acupressure mat and pillow set with 6,210 pressure points. Relieves back tension and promotes relaxation.",
  featured: false
},
{
  id: 82,
  name: "Jump Rope",
  price: 17.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product82.jpg",
  badge: null,
  rating: 4.7,
  reviews: 347,
  description: "Speed jump rope with ball-bearing handles and adjustable steel cable. Suitable for beginners to advanced athletes.",
  featured: false
},
{
  id: 83,
  name: "Bluetooth Tracker",
  price: 26.99,
  originalPrice: null,
  category: "electronics",
  image: "images/product83.jpg",
  badge: "New",
  rating: 4.5,
  reviews: 418,
  description: "Compact Bluetooth item tracker for keys, bags, and wallets. 90m range, replaceable CR2032 battery, app-enabled.",
  featured: false
},
{
  id: 84,
  name: "LED Strip Lights",
  price: 22.99,
  originalPrice: null,
  category: "electronics",
  image: "images/product84.jpg",
  badge: null,
  rating: 4.6,
  reviews: 583,
  description: "5m RGB LED strip lights with app and remote control. Self-adhesive backing, cuttable every 3 LEDs. USB powered.",
  featured: false
},
{
  id: 85,
  name: "Wireless Charger Pad",
  price: 24.99,
  originalPrice: 32.99,
  category: "electronics",
  image: "images/product85.jpg",
  badge: "Sale",
  rating: 4.6,
  reviews: 397,
  description: "15W Qi wireless charging pad compatible with all Qi-enabled devices. Ultra-thin, non-slip surface, LED indicator.",
  featured: false
},
{
  id: 86,
  name: "Mini Projector",
  price: 99.99,
  originalPrice: 129.99,
  category: "electronics",
  image: "images/product86.jpg",
  badge: "Sale",
  rating: 4.4,
  reviews: 134,
  description: "Portable 1080p-supported mini projector with built-in speaker, HDMI and USB inputs. Projects up to 120 inches.",
  featured: false
},
{
  id: 87,
  name: "Skincare Fridge",
  price: 54.99,
  originalPrice: null,
  category: "home",
  image: "images/product87.jpg",
  badge: "New",
  rating: 4.7,
  reviews: 176,
  description: "4L compact skincare mini fridge with whisper-quiet operation. Cools and warms. USB and wall plug included.",
  featured: false
},
{
  id: 88,
  name: "Foot Massager",
  price: 49.99,
  originalPrice: 64.99,
  category: "home",
  image: "images/product88.jpg",
  badge: "Sale",
  rating: 4.7,
  reviews: 228,
  description: "Electric shiatsu foot massager with heat function, 3 intensity levels, and 5 massage modes. Foldable for storage.",
  featured: false
},
{
  id: 89,
  name: "Bread Box",
  price: 33.99,
  originalPrice: null,
  category: "home",
  image: "images/product89.jpg",
  badge: null,
  rating: 4.6,
  reviews: 142,
  description: "Stainless steel roll-top bread box with ventilation slots to keep bread fresh longer. 37x20x18cm.",
  featured: false
},
{
  id: 90,
  name: "Herb Garden Kit",
  price: 27.99,
  originalPrice: null,
  category: "home",
  image: "images/product90.jpg",
  badge: "New",
  rating: 4.8,
  reviews: 267,
  description: "Indoor herb garden kit with 5 seed varieties, biodegradable pots, soil discs, and plant markers. Grow basil, mint, and more.",
  featured: false
},
{
  id: 91,
  name: "Portable Fan",
  price: 31.99,
  originalPrice: null,
  category: "electronics",
  image: "images/product91.jpg",
  badge: null,
  rating: 4.5,
  reviews: 319,
  description: "USB-C rechargeable desk fan with 3 speeds, 4000mAh battery, and 360° rotation. Silent motor at under 25dB.",
  featured: false
},
{
  id: 92,
  name: "Travel Pillow",
  price: 23.99,
  originalPrice: 29.99,
  category: "accessories",
  image: "images/product92.jpg",
  badge: "Sale",
  rating: 4.7,
  reviews: 408,
  description: "Memory foam travel neck pillow with machine-washable cover and snap buckle. Compresses to half its size for packing.",
  featured: false
},
{
  id: 93,
  name: "Packing Cubes Set",
  price: 28.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product93.jpg",
  badge: null,
  rating: 4.8,
  reviews: 492,
  description: "Set of 6 lightweight nylon packing cubes in 3 sizes. Double-zip closure and mesh top panel. Fits any luggage.",
  featured: false
},
{
  id: 94,
  name: "Luggage Tag",
  price: 12.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product94.jpg",
  badge: "New",
  rating: 4.7,
  reviews: 284,
  description: "Genuine leather luggage tag with privacy flap, stainless steel loop, and a window for your contact card.",
  featured: false
},
{
  id: 95,
  name: "Hand Cream Set",
  price: 22.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product95.jpg",
  badge: null,
  rating: 4.8,
  reviews: 371,
  description: "Gift set of 3 nourishing hand creams in Rose, Coconut, and Shea Butter scents. 75ml each. Vegan and cruelty-free.",
  featured: false
},
{
  id: 96,
  name: "Lip Balm Set",
  price: 13.99,
  originalPrice: null,
  category: "accessories",
  image: "images/product96.jpg",
  badge: "New",
  rating: 4.7,
  reviews: 318,
  description: "Set of 5 natural beeswax lip balms in Original, Vanilla, Mint, Cherry, and Coconut. SPF 15 formula.",
  featured: false
},
];
